enum RolePermission{

  //USER
  VIEW_USER,
  CREATE_USER,
  UPDATE_USER,
  DELETE_USER,

  //ROLE
  VIEW_ROLE,
  CREATE_ROLE,
  UPDATE_ROLE,
  DELETE_ROLE,

  //PRODUCT
  VIEW_PRODUCT,
  CREATE_PRODUCT,
  UPDATE_PRODUCT,
  DELETE_PRODUCT,

  //BRAND
  VIEW_BRAND,
  CREATE_BRAND,
  UPDATE_BRAND,
  DELETE_BRAND,

  //CATEGORY
  VIEW_CATEGORY,
  CREATE_CATEGORY,
  UPDATE_CATEGORY,
  DELETE_CATEGORY,

  //PURCHASE
  VIEW_PURCHASE,
  CREATE_PURCHASE,
  UPDATE_PURCHASE,
  DELETE_PURCHASE,

  //SALE
  VIEW_SALE,
  CREATE_SALE,
  UPDATE_SALE,
  DELETE_SALE,

  //STOCK
  VIEW_STOCK,
  CREATE_STOCK,
  UPDATE_STOCK,
  DELETE_STOCK,

  //WEIGHT_LESS
  VIEW_WEIGHT_LESS,
  CREATE_WEIGHT_LESS,
  UPDATE_WEIGHT_LESS,
  DELETE_WEIGHT_LESS,

  //WEIGHT_WASTAGE
  VIEW_WEIGHT_WASTAGE,
  CREATE_WEIGHT_WASTAGE,
  UPDATE_WEIGHT_WASTAGE,
  DELETE_WEIGHT_WASTAGE,

  //WAREHOUSE
  VIEW_WAREHOUSE,
  CREATE_WAREHOUSE,
  UPDATE_WAREHOUSE,
  DELETE_WAREHOUSE,

  //OUTLET
  VIEW_OUTLET,
  CREATE_OUTLET,
  UPDATE_OUTLET,
  DELETE_OUTLET,

  //EXPENSE
  VIEW_EXPENSE,
  CREATE_EXPENSE,
  UPDATE_EXPENSE,
  DELETE_EXPENSE,

  //EXPENSE_CATEGORY
  VIEW_EXPENSE_CATEGORY,
  CREATE_EXPENSE_CATEGORY,
  UPDATE_EXPENSE_CATEGORY,
  DELETE_EXPENSE_CATEGORY,

  //DEPOSIT
  VIEW_DEPOSIT,
  CREATE_DEPOSIT,
  UPDATE_DEPOSIT,
  DELETE_DEPOSIT,

  //DEPOSIT_CATEGORY
  VIEW_DEPOSIT_CATEGORY,
  CREATE_DEPOSIT_CATEGORY,
  UPDATE_DEPOSIT_CATEGORY,
  DELETE_DEPOSIT_CATEGORY,

  //Payment Type
  VIEW_PAYMENT_TYPE,
  CREATE_PAYMENT_TYPE,
  UPDATE_PAYMENT_TYPE,
  DELETE_PAYMENT_TYPE,

}